# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foo.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("foo.proto", :syntax => :proto3) do
    add_message "yuya.takeyama.test.Input" do
    end
    add_message "yuya.takeyama.test.Output" do
    end
  end
end

module Yuya
  module Takeyama
    module Test
      Input = Google::Protobuf::DescriptorPool.generated_pool.lookup("yuya.takeyama.test.Input").msgclass
      Output = Google::Protobuf::DescriptorPool.generated_pool.lookup("yuya.takeyama.test.Output").msgclass
    end
  end
end
