# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: foo.proto for package 'yuya.takeyama.test'

require 'grpc'
require 'foo_pb'

module Yuya
  module Takeyama
    module Test
      module Foo
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'yuya.takeyama.test.Foo'

          rpc :Unary, Input, Output
          rpc :ClientStream, stream(Input), Output
          rpc :ServerStream, Input, stream(Output)
          rpc :BidiStream, stream(Input), stream(Output)
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
